CREATE TYPE PUBLIC."account_type" AS ENUM('Client', 'Employee', 'Admin');

CREATE TABLE IF NOT EXISTS PUBLIC."classification" (
	CLASSIFICATION_ID INT GENERATED BY DEFAULT AS IDENTITY,
	CLASSIFICATION_NAME CHARACTER VARYING NOT NULL,
	CONSTRAINT CLASSIFICATION_PK PRIMARY KEY (CLASSIFICATION_ID)
);

CREATE TABLE IF NOT EXISTS PUBLIC."inventory" (
	INV_ID INT GENERATED BY DEFAULT AS IDENTITY,
	INV_MAKE CHARACTER VARYING NOT NULL,
	INV_MODEL CHARACTER VARYING NOT NULL,
	INV_YEAR CHARACTER(4) NOT NULL,
	INV_DESCRIPTION TEXT NOT NULL,
	INV_IMAGE CHARACTER VARYING NOT NULL,
	INV_THUMBNAIL CHARACTER VARYING NOT NULL,
	INV_PRICE NUMERIC(9, 0) NOT NULL,
	INV_MILES INTEGER NOT NULL,
	INV_COLOR CHARACTER VARYING NOT NULL,
	CLASSIFICATION_ID INTEGER NOT NULL,
	CONSTRAINT INVENTORY_PKEY PRIMARY KEY (INV_ID)
);

ALTER TABLE IF EXISTS PUBLIC."inventory"
ADD CONSTRAINT FK_CLASSIFICATION FOREIGN KEY (CLASSIFICATION_ID) REFERENCES PUBLIC.CLASSIFICATION (CLASSIFICATION_ID) MATCH SIMPLE ON UPDATE CASCADE ON DELETE NO ACTION;

CREATE TABLE IF NOT EXISTS PUBLIC.ACCOUNT (
	ACCOUNT_ID INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	ACCOUNT_FIRSTNAME CHARACTER VARYING NOT NULL,
	ACCOUNT_LASTNAME CHARACTER VARYING NOT NULL,
	ACCOUNT_EMAIL CHARACTER VARYING NOT NULL,
	ACCOUNT_PASSWORD CHARACTER VARYING NOT NULL,
	ACCOUNT_TYPE ACCOUNT_TYPE NOT NULL DEFAULT 'Client'::ACCOUNT_TYPE,
	CONSTRAINT ACCOUNT_PKEY PRIMARY KEY (ACCOUNT_ID)
);

-- Data for table `classification`
INSERT INTO
	PUBLIC.CLASSIFICATION (CLASSIFICATION_NAME)
VALUES
	('Custom'),
	('Sport'),
	('SUV'),
	('Truck'),
	('Sedan');

-- Data for table `inventory`
INSERT INTO
	PUBLIC.INVENTORY (
		INV_MAKE,
		INV_MODEL,
		INV_YEAR,
		INV_DESCRIPTION,
		INV_IMAGE,
		INV_THUMBNAIL,
		INV_PRICE,
		INV_MILES,
		INV_COLOR,
		CLASSIFICATION_ID
	)
VALUES
	(
		'Chevy',
		'Camaro',
		'2018',
		'If you want to look cool this is the ar you need! This car has great performance at an affordable price. Own it today!',
		'/images/camaro.jpg',
		'/images/camaro-tn.jpg',
		25000,
		101222,
		'Silver',
		2
	),
	(
		'Batmobile',
		'Custom',
		'2007',
		'Ever want to be a super hero? now you can with the batmobile. This car allows you to switch to bike mode allowing you to easily maneuver through traffic during rush hour.',
		'/images/batmobile.jpg',
		'/images/batmobile-tn.jpg',
		65000,
		29887,
		'Black',
		1
	),
	(
		'FBI',
		'Surveillance Van',
		'2016',
		'Do you like police shows? You will feel right at home driving this van, comes complete with survalence equipments for and extra fee of $2,000 a month.',
		'/images/survan.jpg',
		'/images/survan-tn.jpg',
		20000,
		19851,
		'Brown',
		1
	),
	(
		'Dog ',
		'Car',
		'1997',
		'Do you like dogs? Well this car is for you straight from the 90s from Aspen, Colorado we have the orginal Dog Car complete with fluffy ears.',
		'/images/dog-car.jpg',
		'/images/dog-car-tn.jpg',
		35000,
		71632,
		'White',
		1
	),
	(
		'Jeep',
		'Wrangler',
		'2019',
		'The Jeep Wrangler is small and compact with enough power to get you where you want to go. Its great for everyday driving as well as offroading weather that be on the the rocks or in the mud!',
		'/images/wrangler.jpg',
		'/images/wrangler-tn.jpg',
		28045,
		41205,
		'Yellow',
		3
	),
	(
		'Lamborghini',
		'Adventador',
		'2016',
		'This V-12 engine packs a punch in this sporty car. Make sure you wear your seatbelt and obey all traffic laws. ',
		'/images/adventador.jpg',
		'/images/adventador-tn.jpg',
		417650,
		71003,
		'Blue',
		2
	),
	(
		'Aerocar International',
		'Aerocar',
		'1963',
		'Are you sick of rushhour trafic? This car converts into an airplane to get you where you are going fast. Only 6 of these were made, get them while they last!',
		'/images/aerocar.jpg',
		'/images/aerocar-tn.jpg',
		700000,
		18956,
		'Red',
		1
	),
	(
		'Monster',
		'Truck',
		'1995',
		'Most trucks are for working, this one is for fun. This beast comes with 60 inch tires giving you traction needed to jump and roll in the mud.',
		'/images/monster-truck.jpg',
		'/images/monster-truck-tn.jpg',
		150000,
		3998,
		'purple',
		1
	),
	(
		'Cadillac',
		'Escalade',
		'2019',
		'This stylin car is great for any occasion from going to the beach to meeting the president. The luxurious inside makes this car a home away from home.',
		'/images/escalade.jpg',
		'/images/escalade-tn.jpg',
		75195,
		41958,
		'Black',
		4
	),
	(
		'GM',
		'Hummer',
		'2016',
		'Do you have 6 kids and like to go offroading? The Hummer gives you the small interiors with an engine to get you out of any muddy or rocky situation.',
		'/images/hummer.jpg',
		'/images/hummer-tn.jpg',
		58800,
		56564,
		'Yellow',
		4
	),
	(
		'Mechanic',
		'Special',
		'1964',
		'Not sure where this car came from. however with a little tlc it will run as good a new.',
		'/images/mechanic.jpg',
		'/images/mechanic-tn.jpg',
		100,
		200125,
		'Rust',
		5
	),
	(
		'Ford',
		'Model T',
		'1921',
		'The Ford Model T can be a bit tricky to drive. It was the first car to be put into production. You can get it in any color you want as long as it is black.',
		'/images/model-t.jpg',
		'/images/model-t-tn.jpg',
		30000,
		26357,
		'Black',
		5
	),
	(
		'Mystery',
		'Machine',
		'1999',
		'Scooby and the gang always found luck in solving their mysteries because of there 4 wheel drive Mystery Machine. This Van will help you do whatever job you are required to with a success rate of 100%.',
		'/images/mystery-van.jpg',
		'/images/mystery-van-tn.jpg',
		10000,
		128564,
		'Green',
		1
	),
	(
		'Spartan',
		'Fire Truck',
		'2012',
		'Emergencies happen often. Be prepared with this Spartan fire truck. Comes complete with 1000 ft. of hose and a 1000 gallon tank.',
		'/images/fire-truck.jpg',
		'/images/fire-truck-tn.jpg',
		50000,
		38522,
		'Red',
		4
	),
	(
		'Ford',
		'Crown Victoria',
		'2013',
		'After the police force updated their fleet these cars are now available to the public! These cars come equiped with the siren which is convenient for college students running late to class.',
		'/images/crwn-vic.jpg',
		'/images/crwn-vic-tn.jpg',
		10000,
		108247,
		'White',
		5
	);

-- taking from assignment2.sql
-- 04: Modify the "GM Hummer" record to read "a huge interior" rather than "small interiors" using a single query
UPDATE PUBLIC."inventory"
SET
	"inv_description" = REPLACE(
		"inv_description",
		'the small interiors',
		'a huge interior'
	)
WHERE
	"inv_id" = 10;

-- taking from assignment2.sql
-- 06: Update all records in the inventory table to add "/vehicles" to the middle of the file path
-- in the inv_image and inv_thumbnail columns using a single query
UPDATE PUBLIC."inventory"
SET
	"inv_image" = REPLACE("inv_image", '/images/', '/images/vehicles/'),
	"inv_thumbnail" = REPLACE("inv_thumbnail", '/images/', '/images/vehicles/');

-- Reviews table for vehicle reviews and ratings
CREATE TABLE IF NOT EXISTS PUBLIC."reviews" (
	REVIEW_ID INT GENERATED BY DEFAULT AS IDENTITY,
	INV_ID INTEGER NOT NULL,
	ACCOUNT_ID INTEGER NOT NULL,
	REVIEW_TEXT TEXT NOT NULL,
	REVIEW_RATING INTEGER NOT NULL CHECK (REVIEW_RATING >= 1 AND REVIEW_RATING <= 5),
	REVIEW_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT REVIEWS_PKEY PRIMARY KEY (REVIEW_ID),
	CONSTRAINT FK_INVENTORY FOREIGN KEY (INV_ID) REFERENCES PUBLIC.INVENTORY (INV_ID) ON DELETE CASCADE,
	CONSTRAINT FK_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES PUBLIC.ACCOUNT (ACCOUNT_ID) ON DELETE CASCADE,
	CONSTRAINT UNIQUE_REVIEW UNIQUE (INV_ID, ACCOUNT_ID)
);